# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a06c88c460e923330c6ac18d6e7f6b1c4aff7c2f250189f707c9ff4c883d05c9afd6d5eed22c73fdb021ecefe3642f55b1104ef1c5694cb8df92b8ffa129598

test:
  secret_key_base: 8f78cb256fbf70cb5146e9c17011fdb79a3002d2f2f4d984c9244b8af752756c69ee72e15508910591fcb525f3fdd06fa89d65e338d081e8c61827673f27947f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
